# roles/Wordpress/tasks/main.yml
---
- name: Install Wordpress (from EPEL)
  yum: pkg={{item}} state=installed
  with_items:
     - wordpress

- name: Apache config file for Wordpress
  copy: 
     src=wordpress.conf
     dest=/etc/httpd/conf.d/wordpress.conf
     owner=root
     group=root
     mode=0644
     setype=httpd_config_t
  notify: Restart Apache
  
- name: Create database
  mysql_db: name={{ wordpress_database }} state=present

- name: Create user
  mysql_user:
      name={{ wordpress_user }}
      state=present
      password={{ wordpress_password }}
      priv="{{ wordpress_database }}.*:ALL,GRANT"

- name: Wordpress config file
  template:
    src=wp-config.php.j2
    dest=/etc/wordpress/wp-config.php
    owner=root
    group=apache
    mode=0640
    setype=etc_t
  notify: Restart Apache